[project]
name = "my_project"
version = "0.1"
dependencies = [
    "flask",
    "flask-socketio",
    "flask-wtf",
]

[project.optional-dependencies]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
